// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Bar is an autogenerated mock type for the Bar type
type Bar struct {
	mock.Mock
}

type Bar_Expecter struct {
	mock *mock.Mock
}

func (_m *Bar) EXPECT() *Bar_Expecter {
	return &Bar_Expecter{mock: &_m.Mock}
}

// IWantWhisky provides a mock function with given fields:
func (_m *Bar) IWantWhisky() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IWantWhisky")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Bar_IWantWhisky_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IWantWhisky'
type Bar_IWantWhisky_Call struct {
	*mock.Call
}

// IWantWhisky is a helper method to define mock.On call
func (_e *Bar_Expecter) IWantWhisky() *Bar_IWantWhisky_Call {
	return &Bar_IWantWhisky_Call{Call: _e.mock.On("IWantWhisky")}
}

func (_c *Bar_IWantWhisky_Call) Run(run func()) *Bar_IWantWhisky_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Bar_IWantWhisky_Call) Return(_a0 string) *Bar_IWantWhisky_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Bar_IWantWhisky_Call) RunAndReturn(run func() string) *Bar_IWantWhisky_Call {
	_c.Call.Return(run)
	return _c
}

// NewBar creates a new instance of Bar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBar(t interface {
	mock.TestingT
	Cleanup(func())
}) *Bar {
	mock := &Bar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
